### ISSUE TITLE
Prepare the first release for obs

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-service-obs#10]
obs has passed the integration tests now, we need to prepare the first release of obs.

## Roadmap

- Add docs in go-storage README and site
- Bump new versions
- Add obs in go-storage-example

**Comment by Xuanwo** [comment]
ping @abyss-w for help

**Comment by abyss-w** [comment]
> ping @abyss-w for help

Got it!

**Comment by abyss-w** [comment]
Done!
